title: Octo
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme


search_enabled: true
color_scheme: "custom-scheme"

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/
baseurl: /octo-cli
heading_anchors: true
# Aux links for the upper right navigation
aux_links:
  "Home":
    - "#"
# Set a path/url to a logo that will be displayed instead of the title
logo: "assets/cover.png"